### PR TITLE
Finalised the second a/b test for the mental health playback.

### PR DESCRIPTION
**Pull request by aikewoody**
# Description

https://www.notion.so/joinzoe/Mental-health-playback-A-B-test-7c6ea57a7d4e4bb48dbe211ea96297bf

https://www.figma.com/file/7TEcX7f6rw3Z0WYR4TpX3R/COVID-Symptom-Study-(App)---MASTER?node-id=12512%3A132033

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

[comment]: <> (Please attach screenshots showing the change, if relevant)

## Checklist (for submission)

- [x] Analytics/tracking events have been added (if relevant)
- [ ] Added new screen(s) to `src/features/screens.ts` and new Redux slice(s) to `mocks/mockedInitialState.ts` (if relevant)

## Checklist (for reviewers)

- [ ] Checked against Figma designs (if relevant)
- [ ] Checked that data has been successfully saved to the backend (if relevant)

## Out of scope and potential follow-up

[comment]: <> (Are there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?)

### CODE REVIEW

**Comment by selvach** [comment]
I'm okay with all the refactors in this PR!

We need to discuss the implementation of `trackMHP()` and `trackScreenViewMHP`

This article (https://help.amplitude.com/hc/en-us/articles/207108327 ) describes the difference between:
 - event_properties (set on a call to `Amplitude.track()`). Needs to be passed on every event if you want to segement and create charts. 
 - user_properties (set on a call to `Amplitdue.identify()`). After setting a user_property ALL events for that user from that point onwards can be filtered by this property when creating charts.

**Comment by aikewoody** [comment]
@selvach Sounds like using `identify` is the easier and also preferred option in this case. You agree on changing `trackMHP` and `trackScreenViewMHP` to the standard functions we already have?

**Comment by selvach** [comment]
Yes! I think that's the preferred approach @aikewoody. 

If you look at the `Experiments.ts` code - at the point you get the user's cohort / group for the experiment you make the `identify()` call. 

https://github.com/zoe/covid-tracker-react-native/blob/bd7f9fcc67b2b220d7f9018e4992253f6433fb06/src/core/Experiments.ts#L34

**Comment by aikewoody** [comment]
> Yes! I think that's the preferred approach @aikewoody.
> 
> If you look at the `Experiments.ts` code - at the point you get the user's cohort / group for the experiment you make the `identify()` call.
> 
> https://github.com/zoe/covid-tracker-react-native/blob/bd7f9fcc67b2b220d7f9018e4992253f6433fb06/src/core/Experiments.ts#L34

Thanks for this suggestion, it made the code a lot simpler!

**Review by selvach — APPROVED** [review]
I gave this a good test! Looks great :)

**Pull request merged**
