### PR TITLE
We need to be able to receive notifications after a reboot!

### PR DESCRIPTION
**Pull request by andyguest**
# Description

_Description of the feature or fix with link to the issue if existing_

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Comment by andyguest** [comment]
Inviting some opinions from the team: will this change fix our problems without introducing other problems for people on upgrade, e.g. if we end up requesting additional permissions and this causes friction / customer support impact?

It is my reading of the docs that "android.permission.RECEIVE_BOOT_COMPLETED" is considered a normal-level permission which no Android system would bother to prompt the user for (because the user cannot say no!).

See: https://developer.android.com/guide/topics/permissions/overview#normal-dangerous
And the reference list here: https://developer.android.com/reference/android/Manifest.permission

**Comment by the-kenneth** [comment]
Put in review im good to try it

**Comment by andyguest** [comment]
@the-kenneth I've done no build / no testing, except to verify that the existing app exhibits a failure to receive notifications after a restart (using the expo tester here https://expo.io/notifications against my personal expo token).  Is this something you would take over on my behalf?

**Comment by the-kenneth** [comment]
I tested with this on and off and in both situations I was able to receive notifications after restarting even when not reopening the app. It did take a few mins sometimes to get them after a reset but they did all come through.

**Pull request closed without merging**
