### PR TITLE
OTA Publish to 0.9.18-ota, 0.12.7-ota, 0.13.7-ota

### PR DESCRIPTION
**Pull request by selvach**
# Description

OTA Publish to `0.9-prod` `0.12-prod` and `0.13-prod`

Tags: 
 - 0.9.18-ota
 - 0.12.7-ota
 - 0.13.7-ota

## On what platform have you tested the change?

- [ ] Android - Emulator
- [x] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist
- [ ] I have updated mockServer

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Comment by abubuwe** [comment]
@MikeD-ZOE does this cause any issues by changing the app.json?

**Comment by selvach** [comment]
No. These diff's are only showing because release-0.x-legacy was cut from develop a while ago. If you compare this the release-0.x-legacy to one of the tagged OTA releases, you'll see what the delta of what will be published.

**Comment by selvach** [comment]
@abubuwe : https://github.com/zoe/covid-tracker-react-native/compare/0.13.7-ota...develop

**Comment by abubuwe** [comment]
@selvach I'm still unclear what that would mean for older app versions on other release channels but if @MikeD-ZOE happy then I can go with that.

**Comment by MikeD-ZOE** [comment]
looks as expected

**Pull request merged**
