### PR TITLE
Feature/sanitize translations

### PR DESCRIPTION
**Pull request by aikewoody**
# Description

Was bored after being sick in bed all day so decided to write a script to sanitise the translations.

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

[comment]: <> (Please attach screenshots showing the change, if relevant)

## Checklist (for submission)

- [ ] Analytics/tracking events have been added (if relevant)
- [ ] Added new screen(s) to `src/features/screens.ts` and new Redux slice(s) to `mocks/mockedInitialState.ts` (if relevant)

## Checklist (for reviewers)

- [ ] Checked against Figma designs (if relevant)
- [ ] Checked that data has been successfully saved to the backend (if relevant)

## Out of scope and potential follow-up

[comment]: <> (Are there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?)

### CODE REVIEW

**Review by bionara — APPROVED** [review]
Beautiful!!

**Comment by selvach** [comment]
Please don't merge yet, I just want to check the translations are properly rendered in Swedish.

**Comment by aikewoody** [comment]
> Please don't merge yet, I just want to check the translations are properly rendered in Swedish.

@selvach Would you have time today to do this? Otherwise let me quickly run it in a simulator and post the results here

**Review by selvach — APPROVED** [review]

**Comment by selvach** [comment]
This is such a great script! Thank you :)

**Comment by aikewoody** [comment]
> @aikewoody - Are the changes to yarn.lock intentional / required?

@selvach Yes, the new dev dependencies needed for the script have a lot of sub dependencies of their own

**Pull request merged**
