### PR TITLE
Custom Switch component

### PR DESCRIPTION
**Pull request by juliatan**
# Description

- This is a custom Switch component based off the React Native Switch component, designed to ZOE brand colours.
- An example of the switch in our Figma designs: https://www.figma.com/file/7TEcX7f6rw3Z0WYR4TpX3R/COVID-Symptom-Study-(App)---MASTER?node-id=12017%3A157720
- Note that it doesn't exactly match what we have in the designs - namely the size of the thumb circle. As I didn't think it was the most high value aspect to be focused on right now, I've left as is for now.
- I'm currently using it in a WIP branch for COVID Test Logging UI changes. To see how I'm using it: https://github.com/zoe/covid-tracker-react-native/blob/b781f35cfe8f312d553a47d67ec67f761431d0de/src/features/covid-tests/fields/CovidTestDateQuestion.tsx#L67
- It made sense for me to keep this Switch component UI-only, with state and logic handled by its parent (which in effect is a Formik state). If need to change this for the NHS app ticket, LMK.

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

Simulator Screen Shot - iPhone 11 - 2021-07-19 at 20 14 17
Simulator Screen Shot - iPhone 11 - 2021-07-19 at 20 14 41

## Checklist (for submission)

- [ ] Analytics/tracking events have been added (if relevant)
- [ ] Added new screen(s) to `src/features/screens.ts` and new Redux slice(s) to `mocks/mockedInitialState.ts` (if relevant)

## Checklist (for reviewers)

- [ ] Checked against Figma designs (if relevant)
- [ ] Checked that data has been successfully saved to the backend (if relevant)

## Out of scope and potential follow-up

[comment]: <> (Are there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?)

### CODE REVIEW

**Review by aikewoody — COMMENTED** [review]
Isn't this the same component as in the other PR? Have you also tested it on Android? I know that the switch component does behave differently in some ways between Android and iOS

**Review by bionara — APPROVED** [review]
Looks great! As @aikewoody mentioned defo worth an Android check too. Approved!

**Comment by juliatan** [comment]
> Isn't this the same component as in the other PR? Have you also tested it on Android? I know that the switch component does behave differently in some ways between Android and iOS

Yep, it's the same component. Just extracting out to separate PR for easy merging ASAP so Ben and Somesh and use it for the Pingdemic feature. 😄 

Android working as expected too. Thanks for requesting the check.
Screenshot_1626773318
Screenshot_1626773325

**Comment by selvach** [comment]
This looks really nice :)

**Pull request merged**
