### PR TITLE
feat(image-cache): cache for 1 week by default

### PR DESCRIPTION
**Pull request by snack-0verflow**
# Description

Images will get cached for a week by default

https://www.npmjs.com/package/react-native-image-cache-wrapper

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Comment by the-kenneth** [comment]
Any reason we are not using a more commonly used library? e.g

https://github.com/kfiroo/react-native-cached-image
or
https://github.com/DylanVann/react-native-fast-image

Just seems maybe a bit better tested/supported?

**Comment by snack-0verflow** [comment]
> Any reason we are not using a more commonly used library? e.g
> 
> https://github.com/kfiroo/react-native-cached-image
> or
> https://github.com/DylanVann/react-native-fast-image
> 
> Just seems maybe a bit better tested/supported?

- `react-native-fast-image` has more opened issues. (But it uses popular native libs under the hood)
- `react-native-cached-image` doesn't support typings
- `react-native-image-cache-wrapper` seems to support typings and easy to set cache timeout

**Comment by the-kenneth** [comment]
> > Any reason we are not using a more commonly used library? e.g
> > https://github.com/kfiroo/react-native-cached-image
> > or
> > https://github.com/DylanVann/react-native-fast-image
> > Just seems maybe a bit better tested/supported?
> 
> * `react-native-fast-image` has more opened issues. (But it uses popular native libs under the hood)
> * `react-native-cached-image` doesn't support typings
> * `react-native-image-cache-wrapper` seems to support typings and easy to set cache timeout

Cool, Im not saying we should use one of the other was just curious at the thought process.

**Comment by snack-0verflow** [comment]
> Is this not working correctly because of the quotes around the "yarn.lock"?
> Is it literally doing a checksum on the string.....

The build will break if there is no qoute marks

**Review by selvach — APPROVED** [review]

**Pull request merged**
