### PR TITLE
Conditional assessment questions

### PR DESCRIPTION
**Pull request by MikeD-ZOE**
# Description

* Frequency of headaches
* Frequency of diarrhoea

## On what platform have you tested the change?

- [X] Android - Emulator
- [ ] Android - Physical device
- [X] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

Simulator Screen Shot - iPhone 8 Plus - 2020-05-04 at 12 20 17
Simulator Screen Shot - iPhone 8 Plus - 2020-05-04 at 12 20 04

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Comment by abubuwe** [comment]
I've made the request for the translation of the additional validation fields also.

**Comment by abubuwe** [comment]
```
"required-diarrhoea-frequency": "Ange hur många gånger du har varit lös i magen det senaste dygnet",
"required-headache-frequency": "Ange hur stor del av dagen du har haft ont i huvudet",
```

**Comment by abubuwe** [comment]
Sorry - just got sent another set of the same translations. 
```
"required-diarrhoea-frequency": ""Ange hur många lösa avföringar du har haft det senaste dygnet",
"required-headache-frequency": "Ange hur stor del av dagen du har haft huvudvärk",
```

**Comment by MikeD-ZOE** [comment]
Added missing Swedish translations.

**Pull request merged**
