### PR TITLE
Feature/updated dropdown field

### PR DESCRIPTION
**Pull request by cm-hvg**
# Description

- Rewrote DropdownField from Class component to Functional component
- Added 5 stories for Storybook (e.g `default`, `multi lines`, `default value`, `no default items`, `with error`)
- Added Storybook addon, `action`. Logging dropdown field's on select action.

## On what platform have you tested the change?

- [x] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [x] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Comment by cm-hvg** [comment]
Cheers @selvach. I can't take much credit, most work is defo from Massimo. 

Almost all changes have been added. with [4] it is not a self closing element. (Is that why you wanted to remove the line?)

**Comment by selvach** [comment]
Sorry - my comment for [4] was to just extract out the inline style into the stylesheet below. Just a minor suggestion for consistency - please ignore if you prefer!

**Comment by cm-hvg** [comment]
@selvach Ah. I just misunderstood, thats all.

**Comment by abubuwe** [comment]
One last comment - can you take a look at the color of the icon? :) 
The design uses `#565A5C` which is the primary color in the colors module, compared to the bluish color that is used.

**Comment by cm-hvg** [comment]
@abubuwe Good spot!

**Pull request merged**
