### PR TITLE
Remove us optional data screen for normal consent

### PR DESCRIPTION
**Pull request by the-kenneth**
# Description

We want to remove the optional data screen for normal US consent users. This is somewhat of a work around as I am modify the county config on the go, but I think its the simplest way, happy for other suggestions.

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

### CODE REVIEW

**Comment by selvach** [comment]
Ugrh.. I understand how this would work and do exactly what the feature requirements as for. But I don't think anyone will be able to intuit why in a few weeks. 

Could we explore a fix that explicitly checks if isUS and isNursesStudy = True and encapsulate the business logic in a function call. 

It's a little sad this can't be done solely through countryConfig.

**Comment by the-kenneth** [comment]
I agree with you Somesh, and am happy to do a little more exploring to see if I can get something cleaner. If not i should comment it at least

**Comment by the-kenneth** [comment]
Ive found a somewhat cleaner approach, this should be better

**Comment by selvach** [comment]
Thanks @the-kenneth !

**Pull request merged**
