### PR TITLE
add banner message to display after loggin vaccine

### PR DESCRIPTION
**Pull request by petermason**
# Description

Uses UI message context to display a Banner after a vaccine has been logged

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

https://user-images.githubusercontent.com/795789/110815222-2ac75d00-8282-11eb-9c41-ebf9bd51167d.mov

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Review by bionara — COMMENTED** [review]
Code looks good (so far!)

**Comment by selvach** [comment]
- Updated the agreed English copy. 
- Waiting on translations from Camilla

**Comment by selvach** [comment]
Final UK Banner

Screenshot 2021-03-15 at 16 57 16

**Comment by selvach** [comment]
Final Swedish Banner (Confirmed by Camilla)

Screenshot 2021-03-15 at 20 39 22

**Review by selvach — APPROVED** [review]

**Pull request merged**
