### PR TITLE
Fix LevelOfIsolation screen appearing weekly.

### PR DESCRIPTION
**Pull request by abubuwe**
# Description

Flip diff on `shouldAskLevelOfIsolation`. It was previously evaluating as negative and never evaluating to true for existing users. 

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

### CODE REVIEW

**Comment by selvach** [comment]
I know it's a one liner. But this is crying out to be turned into a function and a unit test added, please.

**Comment by selvach** [comment]
Done! Spotted a very similar function used in the DaysAgo component.

**Comment by abubuwe** [comment]
Realising this now, but does the explicit conversion to utc() not cause the possible date localisation bug on the profile screen @selvach?

**Comment by selvach** [comment]
@abubuwe Backend always returns UTC. So this code does what it should. 

I think that 1 report by 1 user is somewhat related to timezones. But it might not be.... I'd rather not investigate.

**Comment by selvach** [comment]
@MikeD-ZOE Changes are ready for you to review.

**Pull request merged**
