### PR TITLE
Update Tim's video

### PR DESCRIPTION
**Pull request by selvach**
Screenshot 2020-10-23 at 00 10 55

### CODE REVIEW

**Review by andyguest — APPROVED** [review]
I will grant the approval you crave, but can we please update the thumbnail image otherwise no one will click through - it appears not to have changed for a couple of weeks...

**Comment by selvach** [comment]
New designer is starting on Wednesday. Elana is swamped!

**Comment by the-kenneth** [comment]
@selvach Did you want this to go out today or sometime next week?

**Comment by selvach** [comment]
First thing on Monday AM should be fine - along with #849  as in the video he mentions "Treadlines have been released".

**Comment by selvach** [comment]
@the-kenneth I've updated the asset for Elana for the new blog post. I've also changed the Thumbnail to Tim's video.

**Review by the-kenneth — APPROVED** [review]

**Pull request merged**
