### PR TITLE
Script to compare two locale translation files -- no inheritance.

### PR DESCRIPTION
**Pull request by MikeD-ZOE**
# Description

Simple script to compare a specified strings translation file with the `en` locale one and list missing translations in either.

run with: `npm test:i18n sv-SE` for example. and it picks up a translation string `describe-symptoms.placeholder-has-diarrhoea` that appears in Swedish, but not in the base `en` localisation. And conversely 43 English translation strings with no Swedish equivalent, as expected Optional Info screen, Donations, Cohorts, ethnicities and race. And possibly this: `covid-test.picker-never-had-test`?

This only does one to one matching of locales without taking inheritance into account. That's the next step, perhaps. e.g. Having `es` for generic Spanish, and `es-US` for US-tailores Spanish translations, when checking we should merge `es` and `es-US` and compare that with `en`

UPDATE: Added an `__IGNORE__` block to sv-SE.json so we can implicitly list the translation strings we are not using. What's left are differences we haven't accounted for. And added the script as an npm script (`test:i18n`)

Sample run:

```bash
$ npm run test:i18n sv-SE

> @ test:i18n /Users/miked/Projects-zoe/covid-tracker-react-native
> ts-node ./scripts/i18n-check-locale.ts "sv-SE"

[I18N] Locale: sv-SE
[I18N] Doesn't exist in default: [ 'describe-symptoms.placeholder-has-diarrhoea' ]
[I18N] Missing from sv-SE : [ 'covid-test.picker-never-had-test', 'do-you-use-a-stick' ]
[I18N] Errors: 3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test:i18n: `ts-node ./scripts/i18n-check-locale.ts "sv-SE"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test:i18n script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/miked/.npm/_logs/2020-05-20T16_59_25_635Z-debug.log
```

The script also returns a non-zero exit code if there are errors, which means the npm script can be hooked up to a CI build, and be used to block the build.

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist
- [ ] I have updated mockServer

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Comment by selvach** [comment]
@MikeD-ZOE Please could you either update the readme or add the PR Template checklist, with instructions on how and when to use this script!

**Comment by MikeD-ZOE** [comment]
> Looks great @MikeD-ZOE. Should we add this to CircleCi?

Yes, but we should fix the translation issues found for sv-SE, otherwise it will block on that. :-)

**Comment by julienlavigne** [comment]
Why is that not an automated test? Sounds like a great reason to break the build? No one will run it otherwise

**Comment by MikeD-ZOE** [comment]
> @MikeD-ZOE Please could you either update the readme or add the PR Template checklist, with instructions on how and when to use this script!

Updated README.md and the PR Template checklist.

**Comment by MikeD-ZOE** [comment]
> Why is that not an automated test? Sounds like a great reason to break the build? No one will run it otherwise

Added a unit test that runs the same code.

**Comment by MikeD-ZOE** [comment]
Checks are failing because the unit test introduced has detected discrepancies between `en` and `sv-SE`. These discrepancies have been fixed in PR https://github.com/zoe/covid-tracker-react-native/pull/314 - once in develop, then the CircleCI checks in this PR should pass.

**Pull request merged**
