### PR TITLE
Use the new screen component on multiple screens

### PR DESCRIPTION
**Pull request by aikewoody**
# Description

This branch turned out to be mainly refactors after looking at the legacy code. The biggest refactors are:
- property renamed `step` -> `currentStep`
- removed `JoinHeader` and used `ProgressHeader` instead

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

Only after screenshot (no before, otherwise it would become too large)

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-07-21 at 12 44 18

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-07-21 at 12 44 42

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-07-21 at 12 44 51

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-07-21 at 12 45 01

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-07-21 at 12 45 09

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-07-21 at 12 45 20

Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-07-21 at 12 45 35

## Checklist (for submission)

- [ ] Analytics/tracking events have been added (if relevant)
- [ ] Added new screen(s) to `src/features/screens.ts` and new Redux slice(s) to `mocks/mockedInitialState.ts` (if relevant)

## Checklist (for reviewers)

- [ ] Checked against Figma designs (if relevant)
- [ ] Checked that data has been successfully saved to the backend (if relevant)

## Out of scope and potential follow-up

[comment]: <> (Are there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?)

### CODE REVIEW

**Comment by selvach** [comment]
Really nice refactor and imporvements to the screens!

I'm not a fan of the "ScreenNew" name. Maybe merge all these PRs in and then rename it to something like GenericScreen or just Screen?

**Comment by aikewoody** [comment]
> Really nice refactor and imporvements to the screens!
> 
> I'm not a fan of the "ScreenNew" name. Maybe merge all these PRs in and then rename it to something like GenericScreen or just Screen?

@selvach Agreed, the name will become just `Screen` but to prevent naming collision and confusing during refactoring I decided to go for this temporary name

**Comment by selvach** [comment]
Got it! Okay, can you hold off merging until end of day. Otherwise very happy with these changes!!!

**Review by juliatan — APPROVED** [review]
Nice one Aike! 

Feels like there's definitely going to be merge conflicts with the CovidTest screens that I'm currently amending. What are you plans re: merging in these changes?

**Review by selvach — APPROVED** [review]

**Review by juliatan — APPROVED** [review]

**Review by selvach — APPROVED** [review]

**Pull request merged**
