### PR TITLE
New assessment symptoms flow

### PR DESCRIPTION
**Pull request by the-kenneth**
The main parts of the code to look at are the new files. Additionally did a small refactor around passing parameters to goToNextScreen and around making the assessmentService apis cleaner.

Quite a bit of tidying was done on one or 2 UI components in order to correct an issue with margins. (Touches a lot of files, but a lot was just indentation changes). This code is better just checked by using the app and making sure margins are looking ok in the questions.

### CODE REVIEW

**Comment by the-kenneth** [comment]
Code is ready for review, just missing translations.

**Comment by selvach** [comment]
@the-kenneth This is amazing work! I really like the SymptomCheckBox!

**Review by selvach — APPROVED** [review]

**Comment by selvach** [comment]
Screenshots:

**Comment by selvach** [comment]
Screenshot 2020-11-02 at 14 14 45

**Pull request merged**
