### PR TITLE
Added disabled state to button on About You screen

### PR DESCRIPTION
**Pull request by emma3333**
# Description
Pull request for issue #155  (and related to issue #90) 
Added disabled state to button on About You screen

## On what platform have you tested the change?
* [ ] iOS - Emulator

## Screenshots
Screenshot 2020-04-24 at 09 49 55

# Out of scope and potential follow-up
_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_
n/a

### CODE REVIEW

**Comment by selvach** [comment]
Hell @emma3333 - because some of these inputs are conditional you will need logic similar to this:

```
	                const checkFormFilled = () => {
                            if (Object.keys(errors).length) return false;
                            if (Object.keys(values).length === 0) return false;
                            return true;
                        };
```



```
                                    <BrandedButton
                                        onPress={handleSubmit}
                                        enable={checkFormFilled()}
                                        hideLoading={!isSubmitting}
                                    >
```

**Comment by emma3333** [comment]
Thanks for the feedback @selvach, I'll take a look at this when I get a moment today or tomorrow.

**Comment by emma3333** [comment]
This should now be updated with the correct logic @selvach

**Comment by the-kenneth** [comment]
Hi @emma3333 Can you enable us to push to your PRs by following the instructions in the link below? It will allow us to make small tweaks and merge quicker. Thank you for your contributions!
 
[https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by emma3333** [comment]
Hi,

The pull requests are already set to allow edits from maintainers, is this
what you mean?

Thanks, Emma

**Pull request merged**
