### PR TITLE
WIP: Use the correct Formik way of handling the submit.

### PR DESCRIPTION
**Pull request by aikewoody**
# Description

_Description of the feature or fix with link to the issue if existing_

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevant
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Review by bionara — DISMISSED** [review]

**Review by selvach — COMMENTED** [review]
Would you like to put a simple error message like this?
https://github.com/zoe/covid-tracker-react-native/blob/125ad1345d0d2f9b305d0adebc1a3770f25b2bd3/src/features/multi-profile/edit-profile/EditLocationScreen.tsx#L101

Or would you like to wait for a bigger refactor / clean up of error handling? 

O

**Comment by selvach** [comment]
Tested this for double tapping the button -> two server calls. Looks good to me!

**Comment by selvach** [comment]
Suggestions (can be done in another PR). 
 - Display an error message somewhere on the screen if you get an error from thrown by the API call. 
 - Display a spinner while the server submission is in progress. (i.e. before the screen transition). 

We could use this screen as an example of "how to do formik + server submission correctly.
The main thing is if we use Redux to capture the state, do we transition to the next screen before the server has responed with ("Okay" - I've saved your data)? 

CC: @juliatan @bionara

**Comment by aikewoody** [comment]
> Suggestions (can be done in another PR).
> 
> * Display an error message somewhere on the screen if you get an error from thrown by the API call.
> * Display a spinner while the server submission is in progress. (i.e. before the screen transition).
> 
> We could use this screen as an example of "how to do formik + server submission correctly.
> The main thing is if we use Redux to capture the state, do we transition to the next screen before the server has responed with ("Okay" - I've saved your data)?
> 
> CC: @juliatan @bionara

I like that, this will serve as an example change for the other parts of the codebase 👌

**Comment by juliatan** [comment]
> Suggestions (can be done in another PR).
> 
> * Display an error message somewhere on the screen if you get an error from thrown by the API call.
> * Display a spinner while the server submission is in progress. (i.e. before the screen transition).
> 
> We could use this screen as an example of "how to do formik + server submission correctly.
> The main thing is if we use Redux to capture the state, do we transition to the next screen before the server has responed with ("Okay" - I've saved your data)?
> 
> CC: @juliatan @bionara

Generally speaking (without having context around each form), my thinking process is:

- How important is it that we save the data from the user to the backend e.g. if used to calculate other results, or needed for future reporting, then we shouldn't allow user to proceed to next screen unless data is successfully saved.
- If it's not all that important, then probably makes sense to allow user to proceed so that they're not held up in any way. If this ultimately failed in the backend, it would be treated as lost data though (I don't think it's great UX to have them go back and fill in the form...but we could give them the option to and see if they take it up, though the user journey might be a little complex depending on the form).

**Pull request closed without merging**
