### PR TITLE
Updated native-base to 2.13.14

### PR DESCRIPTION
**Pull request by aikewoody**
# Description

This update fixes all the `useNativeDrive` warnings that show up

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevant
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

### CODE REVIEW

**Comment by selvach** [comment]
In your experience, does this cause problems with Expo OTAs?

**Review by selvach — APPROVED** [review]

**Comment by selvach** [comment]
Do we need this upgrade for any particular feature? Or is it a nice to have?

**Comment by aikewoody** [comment]
> In your experience, does this cause problems with Expo OTAs?

Because it's only a patch version update this shouldn't cause any problems. To be honest I haven't looked at the release notes from `.8` to `.14` so not 100% sure there aren't new native dependencies. But then again it's just a small update

**Comment by aikewoody** [comment]
> Do we need this upgrade for any particular feature? Or is it a nice to have?

It's a nice to have to get rid of the 'useNativeDrive' warnings during development

**Review by bionara — APPROVED** [review]
Looks good. Confident this won't have any OTA implications :)

**Pull request merged**
